Repository cristianbretti/mopidy, pull requests merged in 2019-02, with the labels that each got.

#22 feat: Add ad-hoc coverage for on_message in actor.py (#9)
  mopidy/audio/actor.py
  tests/audio/test_actor.py
Labels: DIY coverage

#21 feat: Add ad hoc tool for measuring branch coverage for next_track (#3)
  branchCoverage.py
  mopidy/core/tracklist.py
  next_track_unchanged
  next_track_unraveled
Labels: DIY coverage

#28 feat: Ad hoc tool for measuring coverage for _process (#4)
  branchCovProcess.py
  mopidy/audio/scan.py
  process_unchanged
  process_unraveled
Labels: DIY coverage

#25 feat: Add ad-hoc coverage for function play in file playback.py (#1)
  mopidy/core/playback.py
  tests/core/test_playback.py
Labels: DIY coverage

#27 feat: Add tests for zeroconf.py (#17)
  tests/test_zeroconf.py
Labels: Improve coverage

#38 feat: Improve coverage on the four methods in #32, #33, #34, #37
  tests/core/test_playback.py
  tests/mpd/protocol/test_music_db.py
Labels: Improve coverage

#29 fead: Add test case for _process (#14)
  tests/audio/test_scan.py
Labels: Improve coverage

#23 refactor: Decrease CC of _process by 12 (#10)
  mopidy/audio/scan.py
Labels: Reduce CC

#24 refactor: Refactor case of random playing in next_track (#12)
  mopidy/core/tracklist.py
Labels: Reduce CC

#42 feat: adhoc branch coverage method for search in search.py(#6)
  mopidy/local/search.py
  tests/local/test_search.py
Labels: DIY coverage

#13 feat: Add branch coverage for lookup (#2)
  mopidy/core/library.py
  tests/core/test_library.py
Labels: DIY coverage

#16 feat: Add ad-hoc coverage for add (#15)
  mopidy/core/tracklist.py
  tests/core/test_tracklist.py
Labels: DIY coverage

#30 feat: Add tests that improve coverage for tracklist.add (#26)
  tests/core/test_tracklist.py
Labels: Improve coverage

#36 feat: Add tests for get_distinct (#35)
  tests/local/test_json.py
Labels: Improve coverage

#40 feat: Add tests for colorize (#39)
  tests/internal/test_log.py
Labels: Improve coverage

#48 feat: Refactor method play in file playback.py (#43)
  mopidy/core/playback.py
Labels: Reduce CC

#51 feat: refactor lookup method (#44)
  mopidy/core/library.py
Labels: Reduce CC

#50 refactor: Decrease add CC (#45)
  mopidy/core/tracklist.py
Labels: Reduce CC

#54 refactor: Reduce complexity of track_to_mpd_format (#46)
  mopidy/mpd/translator.py
Labels: Reduce CC
